---
caption:            'LD42 Jam Game! (Placeholder title, CHANGE THIS!!!)'
fps:                60
has_solids_manager: false
size:
  width:  960
  height: 540
buttons:
  pressable_buttons:
    quit:
      - 'q'
      - 'escape'

player:
  files:
    - 'player1.png'
    - 'player2.png'
    - 'player3.png'
  intervals:                  0.25
  z_index:                    10
  precision_over_performance: true
  size:
    width:  16
    height: 24
  # NOTE: The Player MUST have a centered origin (both axes),
  #       otherwise its #is_touching_* methods do not work.
  #       (Write a feature for the framework to avoid this in the future)
  origin:
    x: :center
    y: :center
  buttons:
    pressable_buttons:
      test:
        - b  # TODO
      move_left:
        - a
        - left
        - h
      move_right:
        - d
        - right
        - l
      jump:
        - w
        - space
        - up
        - k
  max_velocity:
    x: 200
  velocity_decay:
    x: 750
  base_velocity:
    x: 50
    y: 0
  speed:
    x: 600  # Uses Deltatime
    y: 200  # Does NOT use Deltatime
  quick_turn_around: true
  gravity_force: 1100
  # WARNING: If hover_jump_speed is too high, it might exceed the gravity's velocity decrease.
  # When this happens the jump is stronger than gravity and the player can moon-jump.
  hover_jump_speed:               850
  hover_jump_threshold:           100  # Only apply hover_jump_speed if velocity is larger (faster) than this
  jump_standing_on_block_padding: 4

block:
  files:     'block.png'
  intervals: 0.5

safe_block:
  files:     'safe_block.png'
  intervals: 0.5

unsafe_block:
  files:     'unsafe_block.png'
  intervals: 0.5

level:
  has_solids_manager: true
  origin:
    x: :left
    y: :top

section:
  move_direction:
    x: -1
    y:  0
  # move_speed uses Deltatime
  move_speed:
    x: 50
    y: 0
...
