---
caption:            'LD42 Jam Game! (Placeholder title, CHANGE THIS!!!)'
fps:                60
has_solids_manager: false
size:
  width:  960
  height: 540
buttons_event_handler:
  auto_update: true
  pressable_buttons:
    toggle_music:
      - m
      - button_4
background_color: 0xff_ffffff
background_z_index: -10
background_image:
    file: 'bg/bg_1.png'
    origin:
      x: :left
      y: :top
    z_index: -5
level_names:
  - 'one'
  - 'one-two'
  - 'post'
  - 'post-two'
  - 'post-three'
song_file: 'song.wav'

player:
  position:
    x: 16
    y: 412
  animations:
    idle:
      files:
        - 'player/idle.png'
      intervals: 0.1
    moving:
      files:
        - 'player/moving/moving_1.png'
        - 'player/moving/moving_2.png'
        - 'player/moving/moving_1.png'
        - 'player/moving/moving_3.png'
      intervals:
        - 0.25
    jumping:
      files:
        - 'player/jumping.png'
      intervals: 0.1
  files: 'player/idle.png'
  intervals:                  0.1
  z_index:                    5
  precision_over_performance: :high
  solid_tag:                  :player
  solid_tag_collides_with:
    - :block
    - :block_stuck
  size:
    width:  32
    height: 48
  # NOTE: The Player MUST have a centered origin (both axes),
  #       otherwise its #is_touching_* methods do not work.
  #       (Write a feature for the framework to avoid this in the future)
  origin:
    x: :center
    y: :center
  buttons_event_handler:
    auto_update: false
    pressable_buttons:
      move_left:
        - a
        - left
        - h
      move_right:
        - d
        - right
        - l
      jump:
        - w
        - space
        - up
        - k
        - button_0
        - button_2
        - button_9
        - button_10
  max_velocity:
    x: 400
  velocity_decay:
    x: 800
  base_velocity:
    x: 75
    y: 0
  speed:
    x: 650  # Uses Deltatime
    y: 250  # Does NOT use Deltatime
  quick_turn_around: true
  gravity_force: 1100
  # WARNING: If hover_jump_speed is too high, it might exceed the gravity's velocity decrease.
  # When this happens the jump is stronger than gravity and the player can moon-jump.
  hover_jump_speed:               850
  hover_jump_threshold:           100  # Only apply hover_jump_speed if velocity is larger (faster) than this
  jump_standing_on_block_padding: 4

block:
  precision_over_performance: :medium
  auto_update:                false
  files:                      'platform.png'
  intervals:                  1
  solid_tag:                  :block
  solid_tag_collides_with:    :player

safe_block:
  files:     'platform.png'
  intervals: 1
  solid_tag_collides_with: :player
  z_index: 0

unsafe_block:
  files:
    - 'stars/star_4/star_4.1.png'
    - 'stars/star_4/star_4.2.png'
    - 'stars/star_4/star_4.3.png'
  intervals: 0.6
  solid_tag_collides_with:
    - :player
    - :block_stuck
  z_index: 1

level:
  auto_update:        false
  has_solids_manager: true
  move_interval:      0.03
  solids_manager:
    use_cache: false
  origin:
    x: :left
    y: :top
  buttons_event_handler:
    auto_update: false
    pressable_buttons:
      pause:
        - p
        - escape
        - button_6
        - button_1

section:
  auto_update:        false
  has_solids_manager: false
  # NOTE:
  # Settings in the level's config file under key 'section' takes precedence.
  move_direction:
    x: -1
    y:  0
  # move_speed doesn't use Deltatime
  move_speed:
    x: 5
    y: 0
  image:
    file: 'bg/bg_1.png'
    retro: true
    z_index: -1
    origin:
      x: :left
      y: :top
  origin:
    x: :left
    y: :top

menu_buttons:
    text:       ''
    font_size:  24
    font_name:  'MonoSpace'
    font_color: 0xff_ffffff
    text_alignment:
      x: :left
      y: :center
    border_padding:
      x: 16
      y: 8
    border_color: 0xff_666666
    border_size:
      width:  4
      height: 4
    background_color:  0xff_222222
    active_color:      0xff_cc8822
    hover_colow:       0xff_888888
    pressable:         false
    click_on_mouse_up: true
    position:
      x: 64
      y: 0
    size:
      width:  256
      height: 64
    origin:
      x: :left
      y: :center
    z_index: 10

main_menu:
  z_index:     10
  active:      true
  auto_update: true
  mouse_buttons_event_handler:
    only_mouse_buttons: true
    auto_update: false
  buttons_event_handler:
    auto_update: false
    pressable_buttons:
      start:
        - return
        - space
        - button_6
        - button_0
        - button_2
      quit:
        - escape
        - q
        - button_1
  start:
    text: 'Start Game'
    y: 0.4
  level_select:
    text: 'Select Level'
    y: 0.6
  quit:
    text: 'Quit'
    y: 0.8
  title_image:
    file: 'mainmenu_title.png'
    x: 0.05
    y: 0.1
    size:
      width:  512
      height: 64
    origin:
      x: :left
      y: :top
    z_index: 10
  credits_image:
    file: 'mainmenu_credits.png'
    x: 0.8
    y: 0.8
    size:
      width:  256
      height: 128
    origin:
      x: :right
      y: :bottom

pause_menu:
  z_index:     10
  active:      false
  auto_update: true
  mouse_buttons_event_handler:
    only_mouse_buttons: true
    auto_update: false
  buttons_event_handler:
    auto_update: false
    pressable_buttons:
      continue:
        - p
        - return
        - space
        - button_6
        - button_0
      retry:
        - r
        - button_2
      to_main:
        - q
        - escape
        - button_1
  continue:
    text: 'Continue'
    x: 0.5
    y: 0.5
    origin:
      x: :center
      y: :center
  retry:
    text: 'Retry'
    x: 0.5
    y: 0.6
    origin:
      x: :center
      y: :center
  to_main:
    text: 'To Main Menu'
    x: 0.5
    y: 0.7
    origin:
      x: :center
      y: :center
  title_image:
    file: 'mainmenu_title.png'
    x: 0.5
    y: 0.25
    size:
      width:  512
      height: 64
    origin:
      x: :center
      y: :center
    z_index: 10

death_menu:
  z_index:     10
  active:      false
  auto_update: true
  mouse_buttons_event_handler:
    only_mouse_buttons: true
    auto_update: false
  buttons_event_handler:
    auto_update: false
    pressable_buttons:
      retry:
        - r
        - return
        - space
        - button_0
        - button_6
      to_main:
        - q
        - escape
        - button_1
  retry:
    text: 'Retry'
    x: 0.5
    y: 0.6
    origin:
      x: :center
      y: :center
  to_main:
    text: 'To Main Menu'
    x: 0.5
    y: 0.7
    origin:
      x: :center
      y: :center
  title_image:
    file: 'mainmenu_title.png'
    x: 0.5
    y: 0.25
    size:
      width:  512
      height: 64
    origin:
      x: :center
      y: :center
    z_index: 10

win_menu:
  z_index:     10
  active:      false
  auto_update: true
  mouse_buttons_event_handler:
    only_mouse_buttons: true
    auto_update: false
  buttons_event_handler:
    auto_update: false
    pressable_buttons:
      next:
        - return
        - space
        - n
        - button_0
        - button_6
      to_main:
        - q
        - escape
        - button_1
  next:
    text: 'Next Level'
    x: 0.5
    y: 0.6
    origin:
      x: :center
      y: :center
  to_main:
    text: 'To Main Menu'
    x: 0.5
    y: 0.7
    origin:
      x: :center
      y: :center
  title_image:
    file: 'mainmenu_title.png'
    x: 0.5
    y: 0.25
    size:
      width:  512
      height: 64
    origin:
      x: :center
      y: :center
    z_index: 10

thankyou_textbox:
  x: 0.8
  y: 0.9
  text: 'CONGRATULATIONS, you ran out of SPACE! Thank You For Playing!'
  font_size: 24
  font_name: 'MonoSpace'
  font_color: 0xff_aaaaaa
  text_alignment:
    x: :center
    y: :center
  border_padding:
    x: 0
    y: 0
  border_color: 0x00_000000
  border_size:
    width:  0
    height: 0
  background_color: 0x00_000000
  z_index: 10
  size:
    width:  256
    height: 64
  origin:
    x: :right
    y: :bottom
...
