---
caption:            'LD42 Jam Game! (Placeholder title, CHANGE THIS!!!)'
fps:                60
has_solids_manager: false
size:
  width:  960
  height: 540
buttons_event_handler:
  auto_update: true
  pressable_buttons:
    quit:
      - 'q'
      - 'escape'

level_name: 'dev'  # The name of the directory, containing the Level's sections

player:
  files:
    - 'player.png'
  intervals:                  0.25
  z_index:                    10
  precision_over_performance: :high
  solid_tag:                  :player
  solid_tag_collides_with:
    - :block
    - :block_stuck
  size:
    width:  12
    height: 32
  # NOTE: The Player MUST have a centered origin (both axes),
  #       otherwise its #is_touching_* methods do not work.
  #       (Write a feature for the framework to avoid this in the future)
  origin:
    x: :center
    y: :center
  buttons_event_handler:
    auto_update: false
    pressable_buttons:
      test:
        - b  # TODO
      move_left:
        - a
        - left
        - h
      move_right:
        - d
        - right
        - l
      jump:
        - w
        - space
        - up
        - k
  max_velocity:
    x: 250
  velocity_decay:
    x: 750
  base_velocity:
    x: 50
    y: 0
  speed:
    x: 600  # Uses Deltatime
    y: 250  # Does NOT use Deltatime
  quick_turn_around: true
  gravity_force: 1100
  # WARNING: If hover_jump_speed is too high, it might exceed the gravity's velocity decrease.
  # When this happens the jump is stronger than gravity and the player can moon-jump.
  hover_jump_speed:               850
  hover_jump_threshold:           100  # Only apply hover_jump_speed if velocity is larger (faster) than this
  jump_standing_on_block_padding: 4

block:
  precision_over_performance: :medium
  auto_update:                false
  files:                      'block.png'
  intervals:                  0.5
  solid_tag:                  :block
  solid_tag_collides_with:
    - :player

safe_block:
  files:     'safe_block.png'
  intervals: 0.5
  solid_tag_collides_with: :player
  z_index: 0

unsafe_block:
  files:
    - 'star/star0.png'
    - 'star/star1.png'
    - 'star/star2.png'
    - 'star/star1.png'
  intervals: 0.5
  solid_tag_collides_with:
    - :player
    - :block_stuck
  z_index: 1

level:
  auto_update:        false
  has_solids_manager: true
  move_interval: 0.03
  solids_manager:
    use_cache: false
  origin:
    x: :left
    y: :top

section:
  auto_update:        false
  has_solids_manager: false
  # NOTE:
  # Settings in the level's config file under key 'section' takes precedence.
  move_direction:
    x: -1
    y:  0
  # move_speed doesn't use Deltatime
  move_speed:
    x: 5
    y: 0
  origin:
    x: :left
    y: :top

menu_buttons:
    text:       ''
    font_size:  24
    font_name:  'MonoSpace'
    font_color: 0xff_ffffff
    text_alignment:
      x: :left
      y: :center
    border_padding:
      x: 16
      y: 8
    border_color: 0xff_666666
    border_size:
      width:  4
      height: 4
    background_color:  0xff_222222
    active_color:      0xff_cc8822
    hover_colow:       0xff_888888
    pressable:         false
    click_on_mouse_up: true
    position:
      x: 64
      y: 0
    size:
      width:  256
      height: 64
    origin:
      x: :left
      y: :center

main_menu:
  active: true
  mouse_buttons_event_handler:
    only_mouse_buttons: false
  auto_update: true
  start:
    y: 0.4
  level_select:
    y: 0.6
  quit:
    y: 0.8
...
